CREATE TABLE `coreinventories` (
  `name` varchar(255) NOT NULL,
  `data` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `users` ADD `inventorysettings` LONGTEXT NULL DEFAULT NULL;

-- DELETE FROM `user_inventory`

create table if not exists items
(
    id                int auto_increment       primary key,
    name              varchar(255)             not null,
    label             varchar(255)             not null,
    `limit`           int          default 3   not null,
    rare              int          default 0   not null,
    can_remove        int          default 1   not null,
    type              varchar(255)             not null,
    x                 int          default 1   not null,
    y                 int          default 1   not null,
    category          varchar(255)             not null,
    componentTint     int                      null,
    componentHash     varchar(255)             null,
    backpackModel     int                      null,
    backgroundTexture int                      null,
    description       varchar(255)             null,
    weight            varchar(255) default '1' not null
);

create index category_index
    on items (category);

ALTER TABLE `items` 
  ADD `x` int(11) DEFAULT '1',
  ADD `y` int(11) DEFAULT '1',
  ADD `category` varchar(255) DEFAULT 'misc',
  ADD `componentTint` int(11) DEFAULT NULL,
  ADD `componentHash` varchar(255) DEFAULT NULL,
  ADD `backpackModel` int(11) DEFAULT NULL,
  ADD `backgroundTexture` int(11) DEFAULT NULL,
  ADD `description` varchar(255) NOT NULL DEFAULT 'Un objet',
  ADD `weight` varchar(255) DEFAULT NULL;

insert into items (`id`, `name`, label, `limit`, `rare`, `can_remove`, `type`, `x`, `y`, `category`, `componentTint`, `componentHash`, `backpackModel`, `backgroundTexture`, `description`, `weight`)
values
        (1, 'small_backpack', 'Petit sac', 2, 0, 1, 'backpacks', 3, 4, 'backpacks', null, null, 24, 2, 'Un petit sac', '1'),
        (2, 'medium_bag', 'Moyen sac', 2, 0, 1, 'backpacks', 4, 5, 'backpacks', null, null, 16, 0, 'Un sac moyen', '1'),
        (3, 'large_backpack', 'Grand sac', 2, 0, 1, 'backpacks', 4, 5, 'backpacks', null, null, 13, 0, 'Un grand sac', '1'),

        (4, 'weapon_case', 'Caisse d''arme', 1, 0, 1, 'cases', 9, 4, 'cases', null, null, null, null, 'Une caisse d''arme', '10'),
        (5, 'storage_case', 'Caisse de stockage', 1, 0, 1, 'cases', 7, 5, 'cases', null, null, null, null, 'Un caisse de stockage', '10'),

        (6, 'hat', 'Chapeau', -1, 0, 1, 'hat', 1, 1, 'hat', null, null, null, null, 'Un chapeau', '1'),
        (7, 'tshirt', 'Tee-shirt', -1, 0, 1, 'tshirt', 1, 1, 'tshirt', null, null, null, null, 'Un tee-shirt', '1'),
        (8, 'torso', 'Veste', -1, 0, 1, 'torso', 1, 1, 'torso', null, null, null, null, 'Une veste', '1'),
        (9, 'pants', 'Pantalon', -1, 0, 1, 'pants', 1, 1, 'pants', null, null, null, null, 'Un pantalon', '1'),
        (10, 'shoes', 'Chaussure', -1, 0, 1, 'shoes', 1, 1, 'shoes', null, null, null, null, 'Des chaussures', '1'),
        (11, 'watch', 'Montre', -1, 0, 1, 'watch', 1, 1, 'watch', null, null, null, null, 'Une montre', '1'),

        (12, 'weapon_pistol_mk2', 'Glock-20', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet Glock-20', '5'),
        (13, 'weapon_snspistol_mk2', 'Pistolet SNS MK2', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet SNS MK2', '5'),
        (14, 'weapon_pistol', 'Pistolet 9mm', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet 9mm', '5'),
        (15, 'weapon_combatpistol', 'Pistolet de combat', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet de combat', '5'),
        (16, 'weapon_appistol', 'Pistolet automatique', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet automatique', '5'),
        (17, 'weapon_pistol50', 'Pistolet Calibre .50', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet Calibre .50', '5'),
        (18, 'weapon_snspistol', 'Pistolet SNS', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet SNS', '5'),
        (19, 'weapon_heavypistol', 'Pistolet lourd', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet lourd', '5'),
        (20, 'weapon_vintagepistol', 'Pistolet vintage', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet vintage', '5'),
        (21, 'weapon_machinepistol', 'Pistolet mitrailleur', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet mitrailleur', '5'),
        (22, 'weapon_marksmanpistol', 'Pistolet markman', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet markman', '5'),
        (23, 'weapon_revolver_mk2', 'Revolver MK2', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Revolver MK2', '5'),
        (24, 'weapon_revolver', 'Revolver', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Revolver', '5'),
        (25, 'weapon_doubleaction', 'Revolver double action', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Revolver double action', '5'),
        (26, 'weapon_stungun', 'Tazer', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Tazer', '5'),
        (27, 'weapon_flaregun', 'Pistolet à fusé de détresse', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pistolet à fusé de détresse', '5'),

        (28, 'weapon_katana', 'Katana', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Katana', '2.5'),
        (29, 'weapon_metaldetector', 'Detecteur de métaux', 3, 0, 1, 'weapons', 3, 2, 'weapons', null, null, null, null, 'Detecteur de métaux', '2.5'),
        (30, 'weapon_fireaxe', 'Hache de pompier', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Hache de pompier', '2.5'),
        (31, 'weapon_knuckle', 'Poing américain', 3, 0, 1, 'weapons', 2, 2, 'weapons', null, null, null, null, 'Poing américain', '2.5'),
        (32, 'weapon_flashlight', 'Lampe torche', 3, 0, 1, 'weapons', 3, 2, 'weapons', null, null, null, null, 'Lampe torche', '2.5'),
        (33, 'weapon_wrench', 'Clef à molette', 3, 0, 1, 'weapons', 3, 2, 'weapons', null, null, null, null, 'Clef à molette', '2.5'),
        (34, 'weapon_bottle', 'Bouteille cassée', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Bouteille cassée', '2.5'),
        (35, 'weapon_hatchet', 'Hache', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Hache', '2.5'),
        (36, 'weapon_poolcue', 'Queue de billard cassée', 3, 0, 1, 'weapons', 6, 1, 'weapons', null, null, null, null, 'Queue de billard cassée', '2.5'),
        (37, 'weapon_battleaxe', 'Hache de combat', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Hache de combat', '2.5'),
        (38, 'weapon_machete', 'Machette', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Machette', '2.5'),
        (39, 'weapon_stone_hatchet', 'Hache en pierre', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Hache en pierre', '2.5'),
        (40, 'weapon_switchblade', 'Couteau papillon', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Couteau papillon', '2.5'),
        (41, 'weapon_knife', 'Couteau', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Couteau', '2.5'),
        (42, 'weapon_dagger', 'Dague', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Dague', '2.5'),
        (43, 'weapon_nightstick', 'Matraque', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Matraque', '2.5'),
        (44, 'weapon_hammer', 'Marteau', 3, 0, 1, 'weapons', 4, 2, 'weapons', null, null, null, null, 'Marteau', '2.5'),
        (45, 'weapon_bat', 'Batte de baseball', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Batte de baseball', '2.5'),
        (46, 'weapon_golfclub', 'Club de golf', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Club de golf', '2.5'),
        (47, 'weapon_crowbar', 'Pied de biche', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Pied de biche', '2.5'),

        (48, 'weapon_microsmg', 'Uzi', 3, 0, 1, 'weapons', 6, 2, 'weapons', null, null, null, null, 'Uzi', '10'),
        (49, 'weapon_smg', 'MP5', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'MP5', '10'),
        (50, 'weapon_assaultsmg', 'MP5 d''assaut', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'MP5 d''assaut', '10'),
        (51, 'weapon_smg_mk2', 'MP5 MK2', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'MP5 MK2', '10'),
        (52, 'weapon_minismg', 'Mitrailette scorpion', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'Mitrailette scorpion', '10'),
        (53, 'weapon_compactrifle', 'Mitrailette AKU', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'Mitrailette AKU', '10'),
        (54, 'weapon_combatpdw', 'Mitrailette de defense personnelle', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'Mitrailette de defense personnelle', '10'),
        (55, 'weapon_gusenberg', 'Mitrailette gusenberg', 3, 0, 1, 'weapons', 8, 2, 'weapons', null, null, null, null, 'Mitrailette gusenberg', '10'),

        (56, 'weapon_advancedrifle', 'Fusil d''assaut TAR.21', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut TAR.21', '15'),
        (57, 'weapon_assaultrifle', 'Fusil d''assaut AK.47', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut AK.47', '15'),
        (58, 'weapon_assaultrifle_mk2', 'Fusil d''assaut AK.47 amélioré', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut AK.47 amélioré', '15'),
        (59, 'weapon_bullpuprifle', 'Fusil d''assaut bullup', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut bullup', '15'),
        (60, 'weapon_carbinerifle', 'Fusil d''assaut M4', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut M4', '15'),
        (61, 'weapon_carbinerifle_mk2', 'Fusil d''assaut MK2', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut MK2', '15'),
        (62, 'weapon_specialcarbine', 'Fusil d''assaut G36C', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut G36C', '15'),
        (63, 'weapon_specialcarbine_mk2', 'Fusil d''assaut G36C amélioré', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil d''assaut G36C amélioré', '15'),

        (64, 'weapon_autoshotgun', 'Fusil à pompe compact automatique canon', 3, 0, 1, 'weapons', 4, 4, 'weapons', null, null, null, null, 'Fusil à pompe compact automatique canon', '7.5'),
        (65, 'weapon_dbshotgun', 'Fusil double canon', 3, 0, 1, 'weapons', 5, 2, 'weapons', null, null, null, null, 'Fusil double canon', '7.5'),
        (66, 'weapon_sawnoffshotgun', 'Fusil à cannon scié', 3, 0, 1, 'weapons', 5, 2, 'weapons', null, null, null, null, 'Fusil à cannon scié', '7.5'),
        (67, 'weapon_pumpshotgun_mk2', 'Fusil à pompe MK2', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil à pompe MK2', '12.5'),
        (68, 'weapon_pumpshotgun', 'Fusil à pompe', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil à pompe', '12.5'),
        (69, 'weapon_assaultshotgun', 'Fusil à pompe automatique', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil à pompe automatique', '12.5'),
        (70, 'weapon_bullpupshotgun', 'Fusil à pompe bullpup', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil à pompe bullpup', '12.5'),
        (71, 'weapon_heavyshotgun', 'Fusil à pompe lourd', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil à pompe lourd', '12.5'),

        (72, 'weapon_tacticalrifle', 'Fusil de précision tactique', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil de précision tactique', '20'),
        (73, 'weapon_precisionrifle', 'Fusil de précision 2', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil de précision 2', '20'),
        (74, 'weapon_sniperrifle', 'Fusil de précision', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil de précision', '20'),
        (75, 'weapon_marksmanrifle', 'Fusil de précision marksman', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil de précision marksman', '20'),
        (76, 'weapon_heavysniper', 'Fusil de précision lourd', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil de précision lourd', '20'),
        (77, 'weapon_heavysniper_mk2', 'Fusil de précision lourd MK2', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil de précision lourd MK2', '20'),
        (78, 'weapon_musket', 'Fusil mousquet', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil mousquet', '20'),

        (79, 'weapon_mg', 'Fusil mitrailleur lourd', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil mitrailleur lourd', '20'),
        (80, 'weapon_combatmg', 'Fusil mitrailleur lourd amélioré', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil mitrailleur lourd amélioré', '20'),
        (81, 'weapon_minigun', 'Fusil mitrailleur minigun', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil mitrailleur minigun', '20'),
        (82, 'weapon_railgun', 'Fusil laser', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Fusil laser', '20'),

        (83, 'weapon_hominglauncher', 'Lance roquette a tête chercheuse', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Lance roquette a tête chercheuse', '20'),
        (84, 'weapon_compactlauncher', 'Lance grenade compacte', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Lance grenade compacte', '20'),
        (85, 'weapon_grenadelauncher', 'Lance grenade', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Lance grenade', '20'),
        (86, 'weapon_rpg', 'Lance roquette', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Lance roquette', '20'),
        (87, 'weapon_firework', 'Lance feux d''artifices', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Lance feux d''artifices', '20'),
        (88, 'weapon_stinger', 'Lance roquette stinger', 3, 0, 1, 'weapons', 10, 2, 'weapons', null, null, null, null, 'Lance roquette stinger', '20'),

        (89, 'weapon_grenade', 'Grenade', 3, 0, 1, 'weapons', 2, 2, 'weapons', null, null, null, null, 'Grenade', '2.5'),
        (90, 'weapon_smokegrenade', 'Grenade fumigène', 3, 0, 1, 'weapons', 2, 2, 'weapons', null, null, null, null, 'Grenade fumigène', '2.5'),
        (91, 'weapon_flare', 'Fusé de détresse', 3, 0, 1, 'weapons', 3, 2, 'weapons', null, null, null, null, 'Fusé de détresse', '2.5'),
        (92, 'weapon_bzgas', 'Grenade lacrimogène', 3, 0, 1, 'weapons', 2, 2, 'weapons', null, null, null, null, 'Grenade lacrimogène', '2.5'),
        (93, 'weapon_molotov', 'Cocktail molotov', 3, 0, 1, 'weapons', 2, 2, 'weapons', null, null, null, null, 'Cocktail molotov', '2.5'),
        (94, 'weapon_stickybomb', 'Pain de C4', 3, 0, 1, 'weapons', 3, 2, 'weapons', null, null, null, null, 'Pain de C4', '2.5'),
        (95, 'weapon_pipebomb', 'Bombe artisanalle', 3, 0, 1, 'weapons', 3, 2, 'weapons', null, null, null, null, 'Bombe artisanalle', '2.5'),
        (96, 'weapon_proxmine', 'Mine de proximité', 3, 0, 1, 'weapons', 2, 2, 'weapons', null, null, null, null, 'Mine de proximité', '2.5'),
        (97, 'weapon_fireextinguisher', 'Extincteur CO2', 3, 0, 1, 'weapons', 3, 6, 'weapons', null, null, null, null, 'Extincteur CO2', '10'),
        (98, 'weapon_petrolcan', 'Jerican d''essence', 3, 0, 1, 'weapons', 3, 6, 'weapons', null, null, null, null, 'Jerican d''essence', '10'),
        (99, 'weapon_ball', 'Balle de base ball', 3, 0, 1, 'weapons', 1, 1, 'weapons', null, null, null, null, 'Balle de base ball', '1'),
        (100, 'weapon_snowball', 'Boule de neige', 3, 0, 1, 'weapons', 1, 1, 'weapons', null, null, null, null, 'Boule de neige', '1'),
        (101, 'weapon_handcuffs', 'Menote', 3, 0, 1, 'weapons', 1, 2, 'weapons', null, null, null, null, 'Menote', '5'),

        (102, 'bandage', 'Bandage', 50, 0, 1, 'medical', 2, 1, 'medical', null, null, null, null, 'Un bandage pour soigner les blessures', '1'),
        (103, 'xanax', 'Xanax', 50, 0, 1, 'medical', 1, 1, 'medical', null, null, null, null, 'Un xanax, anxiolitique rapide', '1'),
        (104, 'medicaments', 'Medicaments', 50, 0, 1, 'medical', 1, 1, 'medical', null, null, null, null, 'Un médicament permettant de guerrir de petit symptome', '1'),
        (105, 'chaise_roulante', 'Chaise Roulante', 50, 0, 1, 'medical', 4, 4, 'medical', null, null, null, null, 'Une chaise roulante pour les personnes à mobilité réduite', '1'),

        (106, 'weed', 'Têtes de Weed', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Une Têtes de Weed', '1'),
        (107, 'coke', 'Cocaïne', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Cocaïne', '1'),
        (108, 'cocaine', 'Cocaïne', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Trace de cocaine', '1'),
        (109, 'meth', 'Pseudoephedrine', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Pseudoephedrine', '1'),
        (110, 'opium', 'Opium', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Opium', '1'),
        (111, 'ecstasy', 'Ecstasy', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Ecstasy', '1'),
        (112, 'heroine', 'Heroine', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Héroïne', '1'),
        (113, 'crystal', 'Méthénamine', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'Méthénamine', '1'),
        (114, 'lsd', 'LSD', 50, 0, 1, 'drug', 2, 2, 'drug', null, null, null, null, 'An item', '1'),
        (115, 'weed_pooch', 'Pochon de Cannabis', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli de canabis. Peut être vendu ou consommé', '1'),
        (116, 'coke_pooch', 'Pochon de Cocaïne', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli de cocaine. Peut être vendu ou consommé', '1'),
        (117, 'meth_pooch', 'Pochon de Meth', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli de meth. Peut être vendu ou consommé', '1'),
        (118, 'opium_pooch', 'Pochon de opium', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli d''opium. Peut être vendu ou consommé', '1'),
        (119, 'ecstasy_pooch', 'Pochon d''ecstasy', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli d''ecstasy. Peut être vendu ou consommé', '1'),
        (120, 'heroine_pooch', 'Pochon d''heroine', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli d''heroine. Peut être vendu ou consommé', '1'),
        (121, 'lsd_pooch', 'Pochon de LSD', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Un pochon rempli de LSD. Peut être vendu ou consommé', '1'),
        (122, 'engrais', 'Engrais modifié puissant', 50, 0, 1, 'drug', 1, 1, 'drug', null, null, null, null, 'De l''engrais pour booster votre main verte', '1'),
        (123, 'book_weed', 'La Weed pour les nuls', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Vous apprendra tout ce qui est à savoir sur la weed', '1'),
        (124, 'book_meth', 'La Meth pour les nuls', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Vous apprendra tout ce qui est à savoir sur la meth', '1'),
        (125, 'book_coke', 'La Coke pour les nuls', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Vous apprendra tout ce qui est à savoir sur la cocaïne', '1'),
        (126, 'pack_weed', 'Plantes de cannabis', 50, 0, 1, 'drug', 3, 3, 'drug', null, null, null, null, '1 Kg', '1'),
        (127, 'pack_meth', 'Cristaux de meth', 50, 0, 1, 'drug', 3, 3, 'drug', null, null, null, null, '1 Kg', '1'),
        (128, 'pack_coke', 'Plantes de coca', 50, 0, 1, 'drug', 3, 3, 'drug', null, null, null, null, '1 Kg', '1'),
        (129, 'pack_drugs', 'Cargaison de drogues', 50, 0, 1, 'drug', 3, 3, 'drug', null, null, null, null, '1Kg', '1'),
        (130, 'pack_morphine', 'Paquet de morphine', 50, 0, 1, 'drug', 3, 3, 'drug', null, null, null, null, '1 Kg', '1'),
        (131, 'pack_lsd', 'Poudre de LSD', 50, 0, 1, 'drug', 3, 3, 'drug', null, null, null, null, '1 Kg', '1'),
        (132, 'choco_flour', 'Farine chocolat', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Farine aromatisé au chocolat permettant de faire de bon gateau', '1'),
        (133, 'plain_flour', 'Farine', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Farine permettant de faire de bon gateau', '1'),
        (134, 'space_cake', 'Gateau', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un gateau savoureux, mais n''en abusez pas', '1'),
        (135, 'cannabis', 'Cannabis', 50, 0, 1, 'drug', 1, 1, 'drug', null, null, null, null, 'Joint de cannabis', '1'),
        (136, 'lowgradefert', 'Engrais', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Engrais destiné au plantation', '1'),
        (137, 'highgradefert', 'Engrais Boost', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'Engrais puissant destiné au plantation', '1'),
        (138, 'boxweed', 'Kit plantation cannabis', 50, 0, 1, 'drug', 4, 4, 'drug', null, null, null, null, 'Contient le necessaire pour la plantation de canabis', '1'),
        (139, 'dopebag', 'Pochon', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Petit pochon en plastique', '1'),
        (140, 'drugscales', 'Balance', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Permet de mesurer le poid en cuisine', '1'),
        (141, 'highgrademaleseed', 'Grain mâle OGM de cannabis', 50, 0, 1, 'drug', 1, 1, 'drug', null, null, null, null, 'Graine modifié de meilleure qualité pour la plantation de cannabis', '1'),
        (142, 'lowgrademaleseed', 'Graine mâle de cannabis', 50, 0, 1, 'drug', 1, 1, 'drug', null, null, null, null, 'Graine pour la plantation de cannabis', '1'),
        (143, 'highgradefemaleseed', 'Grain femelle OGM de cannabis', 50, 0, 1, 'drug', 1, 1, 'drug', null, null, null, null, 'Graine modifié de meilleure qualité pour la plantation de cannabis', '1'),
        (144, 'lowgradefemaleseed', 'Grain femelle de cannabis', 50, 0, 1, 'drug', 1, 1, 'drug', null, null, null, null, 'Graine pour la plantation de cannabis', '1'),
        (145, 'plantpot', 'Pot', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Pot permettant de planter quelque chose dedans', '1'),
        (146, 'purifiedwater', 'Eau purifiée Boost', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'De l''eau purifié modifiée', '1'),
        (147, 'wateringcan', 'Eau purifiée', 50, 0, 1, 'drug', 1, 2, 'drug', null, null, null, null, 'De l''eau purifié', '1'),
        (148, 'cuivre', 'Cuivre', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Cuivre', '1'),

        (149, 'lockpick', 'Kit de crochetage', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Un kit de crochetage. Permet de forcer les véhicules. Faites attention, c''est fragile', '1'),
        (150, 'mkey', 'Clef magique', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Une clef magique. Permet de forcer les véhicules. Beaucoup plus performant qu''un kit de crochetage', '1'),
        (151, 'robbank', 'Marteau piqueur', 50, 0, 1, 'divers', 6, 2, 'divers', null, null, null, null, 'Un marteau piqueur. Fait céder les sols, les pierres, et même les portes de coffre fort', '1'),
        (152, 'robatm', 'Cracker ATM', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Un cracker d''ATM. Permet de pirater n''importe quel distributeur de billet', '1'),
        (153, 'net_cracker', 'Carte Hack', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une carte très puissante si on sait à quoi elle sert', '1'),
        (154, 'c4brinks', 'Charge C4 (G6 SECURITY)', 50, 0, 1, 'divers', 4, 2, 'divers', null, null, null, null, 'Une charge de C4 permettant de faire exploser les porte d''un camion G6', '1'),
        (155, 'tondeuse', 'Tondeuse', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Une tondeuse. Permet de raser quelqu''un ', '1'),
        (156, 'plate', 'Plaque d''immatriculation', 50, 0, 1, 'divers', 3, 1, 'divers', null, null, null, null, 'Plaque d''immatriculation permettant de changer l''immatriculation d''un véhicule', '1'),
        (157, 'custom_plaque', 'Plaque Custom', 50, 0, 1, 'divers', 3, 1, 'divers', null, null, null, null, 'Plaque d''immatriculation permettant de changer l''immatriculation d''un véhicule', '1'),
        (158, 'cagoule', 'Cagoule', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Cagoule permettant de cacher le visage d''une personne', '1'),
        (159, 'chalumeau', 'Chalumeau', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Un chalumeau portatif', '1'),
        (160, 'usb0c', 'Clef USB 0C', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (161, 'usb0w', 'Clef USB 0W', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (162, 'usb0m', 'Clef USB 0M', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (163, 'usb01', 'Clef USB 01', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (164, 'usb0l', 'Clef USB-0L', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (165, 'usb0v', 'Clef USB 0V', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (166, 'usb_lsd', 'Clef USB-LL', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (167, 'usb_coke', 'Clef USB-LC', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une clef USB chiffrée', '1'),
        (168, 'thermite', 'Bombe Thermique', 10, 0, 1, 'accessoire', 2, 4, 'accessoire', null, null, null, null, 'Une bombe thermite très puissante pour ouvrir des brèches', '1'),
        (169, 'pinceforte', 'Pince à forte pression', 50, 0, 1, 'divers', 1, 4, 'divers', null, null, null, null, '', '1'),

        (170, 'harybo_turbo', 'Kit Turbo', 10, 1, 1, 'admin', 3, 2, 'admin', null, null, null, null, 'Un turbo pour véhicule', '1'),
        (171, 'harybo_medikit', 'Kit spécial Médikit', 10, 1, 1, 'admin', 3, 2, 'admin', null, null, null, null, 'Un kit medical permettant de soigner les blessures', '1'),
        (172, 'harybo_super_medikit', 'Super Médikit', 10, 1, 1, 'admin', 3, 2, 'admin', null, null, null, null, 'Un kit medical permettant de soigner n''importe quelles blessures', '1'),
        (173, 'harybo_drift', 'Kit de drift', 10, 1, 1, 'admin', 3, 2, 'admin', null, null, null, null, 'Un kit permettant de réduire l''adhérence d''un véhicule', '1'),
        (174, 'harybo_nitro', 'NOS', 10, 1, 1, 'admin', 3, 2, 'admin', null, null, null, null, 'Une bombonne de NOS permettant une accélération rapide sur une courte durée', '1'),

        (175, 'tirelire', 'Tirelire', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'La tirelire d''un enfant qui doit pleurer à l''heure qu''il est', '1'),
        (176, 'ps4', 'PS4', 50, 0, 1, 'divers', 3, 2, 'divers', null, null, null, null, 'Console de jeu qui rend abrutis les enfants', '1'),
        (177, 'ordi', 'Ordinateur Portable', 50, 0, 1, 'divers', 3, 2, 'divers', null, null, null, null, 'Ne vérifiez pas l''historique de cet ordinateur, on ne sait jamais', '1'),
        (178, 'montre', 'Montre de Luxe', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'C''est une vrai, et elle en rend jaloux plus d''un', '1'),
        (179, 'bijoux', 'Bijoux', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Un bijoux resplendissant ', '1'),
        (180, 'jeux', 'Jeux Video', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Sans console, vous n''irez pas bien loin avec ça', '1'),
        (181, 'photo', 'Appareil Photo', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Mémorisez vos meilleurs souvenirs, enfin, si c''est le votre', '1'),
        (182, 'camera', 'Camera 4K', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Réveillez le créateur de contenue qui est en vous', '1'),
        (183, 'vetements', 'Vetements de Luxe', 50, 0, 1, 'divers', 2, 3, 'divers', null, null, null, null, 'Personne n''a idée de porter ça', '1'),
        (184, 'jewels', 'Bijoux de Luxe', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Des bijoux resplendissants', '1'),
        (185, 'gold', 'Lingot d''or', 50, 0, 1, 'divers', 2, 4, 'divers', null, null, null, null, 'Lingot d''or d''un kilo.', '1'),
        (186, 'collier_yacht', 'Collier du Yacht', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Un collier qui vaut un sacré paquet d''argent', '1'),
        (187, 'portable', 'ordinateur sous scellés', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Un ordinateur sous scéllé qui contient surement des informations très intéressantes', '1'),

        (188, 'fixkit', 'Kit de réparation', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Kit de réparation de première nécessité pour réparer la panne d''un véhicule', '1'),
        (189, 'cleankit', 'Kit de nettoyage', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Kit de nettoyage. Permet de rendre tout l''éclat de votre véhicule', '1'),
        (190, 'fishingrod', 'Canne à pêche courte', 50, 0, 1, 'divers', 4, 1, 'divers', null, null, null, null, 'Une canne à pêche courte. utiliser avec des appats de vers', '1'),
        (191, 'fishingrod2', 'Canne a pêche longue', 50, 0, 1, 'divers', 6, 1, 'divers', null, null, null, null, 'Une canne à pêche longue. utiliser avec des appats de crabe', '1'),
        (192, 'bbait2', 'Boite d''appat de crabes', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Une boite d''appat de crabe contenant 20 appats. Permet de pêcher', '1'),
        (193, 'bbait', 'Boite d''appat de vers', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Une boite d''appat de vers contenant 20 appats. Permet de pêcher', '1'),
        (194, 'bait2', 'Appat crabe', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Un appat de crabe qui sert à pêcher', '1'),
        (195, 'bait', 'Appat vers', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Un appat de vers qui sert à pêcher', '1'),
        (196, 'ballon', 'Ballon de foot', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Un ballon de foot', '1'),
        (197, 'lilo', 'Matelas gonflable', 50, 0, 1, 'divers', 2, 6, 'divers', null, null, null, null, 'Un matelas gonflable', '1'),
        (198, 'ring', 'Bouée gonflable', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, 'Une bouée gonflable', '1'),
        (199, 'rose', 'Rose', 50, 0, 1, 'divers', 1, 3, 'divers', null, null, null, null, 'Une rose rouge', '1'),
        (200, 'preservatif', 'Preservatif', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Un préservatif. Sortez couvert', '1'),
        (201, 'preser_usag', 'Préservatif usagé', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Débarassez vous de cette chose', '1'),
        (202, 'umbrella', 'Parapluie', 50, 0, 1, 'divers', 1, 4, 'divers', null, null, null, null, 'Un parapluie', '1'),
        (203, 'beachball', 'Ballon de volley', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Un ballon de volley', '1'),
        (204, 'jumelles', 'Jumelles', 50, 0, 1, 'divers', 2, 1, 'divers', null, null, null, null, 'Une paire de jumelle permettant de voir au loin', '1'),
        (205, 'cigarette', 'Cigarette', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Une cigarette. Fumer est dangereux pour la santé.', '1'),
        (206, 'packcig', 'Paquet de cigarette', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Un paquet de cigarette. Contient 10 cigarettes', '1'),
        (207, 'packcigar', 'Paquet de cigare', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Un paquet de cigare. Contient 10 cigares', '1'),
        (208, 'chicha', 'Bang', 50, 0, 1, 'divers', 1, 3, 'divers', null, null, null, null, '', '1'),
        (209, 'cigar', 'Cigar', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Un cigare. Fumer est dangereux pour la santé', '1'),
        (210, 'croquettes', 'Croquettes', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Une croquette. Permet de nourire vos animaux', '1'),
        (211, 'briquet', 'Briquet', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Un briquet. Outil incontournable des fumeurs', '1'),
        (212, 'phone', 'Téléphone', 50, 0, 1, 'divers', 1, 2, 'divers', null, null, null, null, 'Un téléphone. Les gens ne s''en passent plus de nos jours', '1'),
        (213, 'braceletgps', 'Bracelet Électronique', 50, 0, 0, 'divers', 2, 2, 'divers', null, null, null, null, 'Bracelet éléctronique gps permettant de connaitre la position de quelqu''un. Utiliser par les forces de l''ordre', '1'),
        (214, 'braceletgps1', 'Tracker GPS Police', 50, 0, 0, 'divers', 2, 2, 'divers', null, null, null, null, 'Tracker gps permettant de connaitre la position de quelqu''un / quelque chose. Utiliser par les forces de l''ordre', '1'),
        (215, 'braceletgps2', 'Tracker GPS Sheriff', 50, 0, 0, 'divers', 2, 2, 'divers', null, null, null, null, 'Tracker gps permettant de connaitre la position de quelqu''un / quelque chose. Utiliser par les forces de l''ordre', '1'),
        (216, 'braceletgps3', 'Tracker GPS EMS', 50, 0, 0, 'divers', 2, 2, 'divers', null, null, null, null, 'Tracker gps permettant de connaitre la position de quelqu''un / quelque chose. Utiliser par les forces de l''ordre', '1'),
        (217, 'uvlight', 'Lampe UV', 50, 0, 1, 'divers', 3, 1, 'divers', null, null, null, null, 'Permet de relever les empreintes dans les véhicules', '1'),
        (218, 'scuba', 'Tenu de plonger', 50, 0, 1, 'divers', 2, 4, 'divers', null, null, null, null, 'Tenue permettant de nager sous l''eau sans avoir froid ni manquer d''oxygène', '1'),
        (219, 'sim', 'Carte Sim', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Mise dans le téléphone, elle vous permet d''avoir accès au réseaux NebLTE', '1'),
        (220, 'custom_sim', 'Carte Sim Custom', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Mise dans le téléphone, elle vous permet d''avoir accès au réseaux NebLTE', '1'),
        (221, 'bague', 'Bague de Fiancaille', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Rien de mieux pour prouver son amour qu''une bague', '1'),
        (222, 'fw', 'Fontaine artifice', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, 'Feux d''artifice', '1'),
        (223, 'fw2', 'Fusee artifice', 50, 0, 1, 'divers', 2, 3, 'divers', null, null, null, null, 'Feux d''artifice', '1'),
        (224, 'boxe', 'Gants de Boxe', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Permet de se battre sans se faire mal (ou presque)', '1'),
        (225, 'album', 'Album', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, '', '1'),
        (226, 'pinceHair', 'Pince à cheveux', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Une pince pour vous attacher les cheveux lorsque vous avec un chapeau', '1'),
        (227, 'armour25', 'Gilet Pare Balle (leger)', 10, 0, 1, 'accessoire', 4, 4, 'accessoire', null, null, null, null, 'Un gilet par balle léger augmentant la resistance aux balles', '1'),
        (228, 'armour50', 'Gilet Pare Balle (lourd)', 10, 0, 1, 'accessoire', 4, 4, 'accessoire', null, null, null, null, 'Un gilet par balle lourd augmentant la resistance aux balles', '1'),
        (229, 'tablet', 'Tablette', 50, 0, 1, 'divers', 3, 2, 'divers', null, null, null, null, 'Une tablette permettant de naviguer sur le net', '1'),
        (230, 'radio', 'Radio', 50, 0, 1, 'divers', 1, 3, 'divers', null, null, null, null, '', '1'),
        (231, 'jeton', 'Jeton de 100$', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Jeton de jeux du Diamond Casino', '1'),
        (232, 'hifi', 'HiFi', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Une chaine hifi pour vous ambiancez n''importe où', '1'),
        (233, 'carotte', 'Carotte', 10, 1, 1, 'admin', 2, 1, 'admin', null, null, null, null, 'Une carotte, On comprend pouruqoi Bugs Bunny était toujours en forme avec ça', '1'),
        (234, 'super_carotte', 'Wonka bar', 10, 1, 1, 'admin', 2, 1, 'admin', null, null, null, null, 'Rien de tel qu''un privilège bien mérité dans ce monde de brute', '1'),
        (235, 'trailburst', 'Trailburst', 50, 0, 1, 'divers', 1, 3, 'divers', null, null, null, null, 'Feux d''artifice', '1'),
        (236, 'fountain', 'Fountain (Feu d''artifice)', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Feux d''artifice', '1'),
        (237, 'starburst', 'Starburst (Feu d''artifice)', 50, 0, 1, 'divers', 1, 3, 'divers', null, null, null, null, 'Feux d''artifice', '1'),
        (238, 'shotburst', 'Shotburst (Feu d''artifice)', 50, 0, 1, 'divers', 2, 2, 'divers', null, null, null, null, 'Feux d''artifice', '1'),
        (239, 'scratchcard', 'Carte à gratter', 50, 0, 1, 'divers', 1, 1, 'divers', null, null, null, null, 'Une carte à gratter. La ville remet ses coupons pour chaque vote fait', '1'),

        (240, 'carton', 'Carton de marchandises', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (241, 'bouff', 'Marchandises', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (242, 'balcool', 'Carton d''alcool', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (243, 'kits', 'Carton de pieces auto', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (244, 'journal', 'Carton de journal', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (245, 'tabac', 'Carton de feuille de tabac', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (246, 'pfood', 'Commande a livrer', 50, 0, 1, 'divers', 3, 3, 'divers', null, null, null, null, '', '1'),
        (247, 'weapbox', 'Carton d''armes', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (248, 'bcoffee', 'Carton de graines de café', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (249, 'pack_weap', 'Carton d''arme', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (250, 'cpneus', 'Carton de pneus neufs', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),
        (251, 'fcigar', 'Carton de feuille de cigar', 50, 0, 1, 'divers', 4, 4, 'divers', null, null, null, null, '', '1'),

        (252, 'vodka', 'Vodka', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vodka', '1'),
        (253, 'rhum', 'Rhum', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de rhum', '1'),
        (254, 'whisky', 'Whisky', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de whisky', '1'),
        (255, 'tequila', 'Tequila', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de tequila', '1'),
        (256, 'martini', 'Martini blanc', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de martini', '1'),
        (257, 'vodkaenergy', 'Vodka-energy', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vodka energy', '1'),
        (258, 'vodkafruit', 'Vodka jus de fruits', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vodka jus de fruit', '1'),
        (259, 'rhumfruit', 'Rhum jus de fruits', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de rhum jus de fruit', '1'),
        (260, 'teqpaf', 'Teq''paf', 3, 0, 1, 'alcool', 1, 1, 'alcool', null, null, null, null, 'Un shot de teq paf ', '1'),
        (261, 'rhumcoca', 'Rhum coca', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de rhum coca', '1'),
        (262, 'mojito', 'Mojito', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de mojito', '1'),
        (263, 'vinblanc', 'Verre vin blanc', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vin blanc', '1'),
        (264, 'vinrouge', 'Verre vin rouge', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vin rouge', '1'),
        (265, 'sangria', 'Sangria', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de sangria', '1'),
        (266, 'sake', 'Saké', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de saké', '1'),
        (267, 'pinacolada', 'Pinacolada', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Une pinacolada', '1'),
        (268, 'vchampagne', 'Champagne', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Une coupe de champagne', '1'),
        (269, 'vruinart', 'Champagne ruinart', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Une coupe de champagne ruinart', '1'),
        (270, 'vinrose', 'Verre de rosé', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vin rosé', '1'),
        (271, 'vinf', 'Vin framboise', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vin framboise', '1'),
        (272, 'ving', 'Vin au gingembre', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de vin au gingembre', '1'),
        (273, 'beer_lost7', 'Grand Schroumpf', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Un coktail alcolisé bleue', '1'),
        (274, 'annasbanana', 'Anna''s Banana', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un cocktail alcolisé à la banane', '1'),
        (275, 'rhumtini', 'Expresso Rhumtini', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un expresso au rhum', '1'),
        (276, 'tequipaf', 'Tek''Paf', 3, 0, 1, 'drink', 1, 1, 'drink', null, null, null, null, 'Une ''tek paf''', '1'),
        (277, 'margarita', 'Margarita', 3, 0, 1, 'drink', 2, 2, 'drink', null, null, null, null, 'Une margarita, coktail alcolisé', '1'),
        (278, 'hurricane', 'Hurricane', 3, 0, 1, 'drink', 2, 2, 'drink', null, null, null, null, 'Un coktail alcolisé', '1'),
        (279, 'shot_tequila', 'Shot de Tequila', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un shot de tequila', '1'),
        (280, 'shot_vodka', 'Shot de Vodka', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un shot de vodka', '1'),
        (281, 'cubalib', 'Cuba Libre', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un coktail alcolisé', '1'),
        (282, 'tequisun', 'Tequila Sunrise', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Une tequila avec différent jus de fruits', '1'),
        (283, 'bluelag', 'Blue Lagoon', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un cocktail alcolisé', '1'),
        (284, 'shot_b52', 'Whisky Bowmore', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Un verre de whisky bowmore', '1'),
        (285, 'shot_jager', 'Vodka Poctocki', 3, 0, 1, 'alcool', 2, 2, 'alcool', null, null, null, null, 'Une vodka aromatisé', '1'),

        (286, 'beer', 'Biere', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (287, 'beer_lost1', 'Bière In Memoriam', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (288, 'beer_lost2', 'Bière Valhalla', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (289, 'beer_lost3', 'Bière Ace Of Spades', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (290, 'beer_lost4', 'Bière Tombstone', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (291, 'beer_lost5', 'Bière Reconquest', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (292, 'beer_lost6', 'Bière Marbee', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (293, 'beer_lost8', 'Bière Lucky Day', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de bière', '1'),
        (294, 'bvodka', 'Bouteille de vodka', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de vodka. Permet de servir plus ou moins 5 verres', '1'),
        (295, 'bwhisky', 'Bouteille de whisky', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de whisky. Permet de servir plus ou moins 5 verres', '1'),
        (296, 'brhum', 'Bouteille de rhum', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de rhum. Permet de servir plus ou moins 5 verres', '1'),
        (297, 'btequila', 'Bouteille de tequila', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de tequila. Permet de servir plus ou moins 5 verres', '1'),
        (298, 'vrouge', 'Bouteille de rouge', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de vin rouge. Permet de servir plus ou moins 5 verres', '1'),
        (299, 'vblanc', 'Bouteille de blanc', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de vin blanc. Permet de servir plus ou moins 5 verres', '1'),
        (300, 'vrose', 'Bouteille de rosé', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de vin rosé. Permet de servir plus ou moins 5 verres', '1'),
        (301, 'champagne', 'Bouteille champagne', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de champagne. Permet de servir plus ou moins 5 verres', '1'),
        (302, 'ruinart', 'Bouteille ruinart', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de champagne ruinart. Permet de servir plus ou moins 5 verres', '1'),
        (303, 'bvinf', 'Bouteille Vin framboise', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de vin framboise. Permet de servir plus ou moins 5 verres', '1'),
        (304, 'bving', 'Bouteille Vin gingembre', 3, 0, 1, 'alcool', 1, 3, 'alcool', null, null, null, null, 'Une bouteille de vin gingembre. Permet de servir plus ou moins 5 verres', '1'),
        (305, 'water', 'Bouteille d''eau', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Une bouteille d''eau pour vous hydrater', '1'),

        (306, 'soda', 'Soda', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un soda pour vous hydrater', '1'),
        (307, 'jusfruit', 'Jus de fruits', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un jus de fruit pour vous hydrater', '1'),
        (308, 'icetea', 'Ice Tea', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un ice tea pour vous hydrater', '1'),
        (309, 'energy', 'Energy Drink', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Une boisson energisante pour vous hydrater', '1'),
        (310, 'fanta', 'Fanta', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un fanta pour vous hydrater', '1'),
        (311, 'pepsi', 'Pepsi', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un pepsi pour vous hydrater', '1'),
        (312, 'orangina', 'Orangina', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un orangina pour vous hydrater', '1'),
        (313, 'panache', 'Panaché', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un panaché pour vous hydrater', '1'),
        (314, 'sprunk', 'Sprunk', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un Sprunk pour vous hydrater', '1'),
        (315, 'coca', 'Coca', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un coca pour vous hydrater', '1'),
        (316, 'coffee', 'Café', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un café pour vous hydrater', '1'),
        (317, 'chocolatc', 'Chocolat Chaud', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un chocolat chaud pour vous hydrater', '1'),
        (318, 'cappuccino', 'Cappuccino', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un capuccino pour vous hydrater', '1'),
        (319, 'caprisun', 'Capri-Sun', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un caprisun pour vous hydrater', '1'),
        (320, 'chinotto', 'Chinotto', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un chinotto pour vous hydrater', '1'),
        (321, 'the', 'Thé', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Une tasse de thé pour vous hydrater', '1'),
        (322, 'limonade', 'Le Cowboy Coktail', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un cowboy coktail pour vous hydrater', '1'),
        (323, 'mocaccino', 'Mocaccino', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un Mocaccino pour vous hydrater', '1'),
        (324, 'cafe_frappe', 'Expresso', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un expresso pour vous hydrater', '1'),
        (325, 'caramel_macchiato', 'Caramel Macchiato', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un caramel macchiato pour vous hydrater', '1'),
        (326, 'chocolate_chaud_tiramisu', 'Chocolat chaud tiramisu', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un chocolat chaud tiramisu pour vous hydrater', '1'),
        (327, 'bubbletea', 'Le petit indien', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un petit indien pour vous hydrater', '1'),
        (328, 'grandmatea', 'Thé de grand-mère', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un thé de grand mère pour vous hydrater', '1'),
        (329, 'monaco', 'Monaco', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Un monaco pour vous hydrater', '1'),
        (330, 'btlait', 'Root beer', 3, 0, 1, 'drink', 1, 2, 'drink', null, null, null, null, 'Root beer pour vous hydrater', '1'),
        (331, 'irish_coffee', 'Irish Coffee', 3, 0, 1, 'drink', 1, 1, 'drink', null, null, null, null, 'Un irish coffee pour vous hydrater', '1'),

        (332, 'bolcacahuetes', 'Bol de cacahuètes', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Bol de cacahuètes. Utile en cas de petite faim', '1'),
        (333, 'bolnoixcajou', 'Bol de noix de cajou', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Bol de noix de cajou. Utile en cas de petite faim', '1'),
        (334, 'bolpistache', 'Bol de pistaches', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Bol de pistaches. Utile en cas de petite faim', '1'),
        (335, 'bolchips', 'Bol de chips', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Bol de chips. Utile en cas de petite faim', '1'),
        (336, 'saucisson', 'Saucisson', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Saucisson. Utile en cas de petite faim', '1'),
        (337, 'fish', 'Poisson bar', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Poisson bar. Utile en cas de petite faim', '1'),
        (338, 'olives', 'Olives pimentées', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Olives pimentées. Utile en cas de petite faim', '1'),
        (339, 'durum', 'Glace', 3, 0, 1, 'eat', 1, 2, 'eat', null, null, null, null, 'Glace. Utile en cas de petite faim', '1'),
        (340, 'panacotta', 'Panacotta', 3, 0, 1, 'eat', 1, 2, 'eat', null, null, null, null, 'Panacotta. Utile en cas de petite faim', '1'),
        (341, 'hotdog', 'Hotdog', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'HotDog. Utile en cas de petite faim', '1'),
        (342, 'coffee_sandwich', 'Club Sandwich Poulet', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Club sandwitch poulet. Utile en cas de petite faim', '1'),
        (343, 'tiramissu', 'Tiramisu', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Tiramisu. Utile en cas de petite faim', '1'),
        (344, 'ceviche', 'Salade Ceviche', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Une salade ceviche. Utile en cas de petite faim', '1'),
        (345, 'croquem', 'Croque monsieur', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Un croque monsieur. Utile en cas de petite faim', '1'),
        (346, 'croquemm', 'Croque madame', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Un croque madame. Utile en cas de petite faim', '1'),
        (347, 'corne_gazelle', 'Corne de gazelle', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Une corne de gazelle. Utile en cas de petite faim', '1'),
        (348, 'corngrilled', 'Mais grillé', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un épi de maïs grillé. Utile en cas de petite faim', '1'),
        (349, 'mochiyoshi', 'Texan Ribs', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Un texan ribs pour vous hydrater', '1'),
        (350, 'dangoventi', 'Arizona Spicy Beef', 3, 0, 1, 'eat', 2, 1, 'eat', null, null, null, null, 'Un Arizona Spicy Beef. Utile en cas de petite faim', '1'),
        (351, 'candy', 'Bonbons', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Des bonbons. Utile en cas de très petite faim', '1'),
        (352, 'pancake', 'Pancake', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un pancake. Utile en cas de petite faim', '1'),
        (353, 'gaufre', 'Gaufre', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Une gauffre. Utile en cas de petite faim', '1'),
        (354, 'frites', 'Frites', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Des frites. Utile en cas de petite faim', '1'),
        (355, 'parisbrest', 'Ribbs', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Des Ribbs. Utile en cas de petite faim', '1'),
        (356, 'donut', 'Donut', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un donuts. Utile en cas de petite faim', '1'),
        (357, 'kitkat', 'Kitkat', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un Kitkat. Utile en cas de petite faim', '1'),
        (358, 'twix', 'Twix', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un twix. Utile en cas de petite faim', '1'),
        (359, 'salade', 'Salade Atom', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Une salade atom. Utile en cas de petite faim', '1'),
        (360, 'partpizza', 'Part de pizza', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une part de pizza. Utile en cas de petite faim', '1'),
        (361, 'oplat', 'Salade de fruit', 3, 0, 1, 'eat', 1, 2, 'eat', null, null, null, null, 'Une salade de fruit. Utile en cas de petite faim et soif', '1'),
        (362, 'cesarsalad', 'Poulet Kentucky', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un poulet Kentucky. Utile en cas de petite faim', '1'),
        (363, 'oeufmimo', 'Pommes de terres au four', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Des pommes de terres au four. Utile en cas de petite faim', '1'),
        (364, 'tarte', 'Tarte au pommes', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Une tarte. Utile en cas de petite faim', '1'),
        (365, 'cookies', 'Cookies', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un cookies. Utile en cas de petite faim', '1'),
        (366, 'pokebowl', 'Pokebowl', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un pokeball. Utile en cas de petite faim', '1'),
        (367, 'cheesecake', 'Croissant', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un croissant. Utile en cas de petite faim', '1'),
        (368, 'muffins', 'Muffins', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un Muffins. Utile en cas de petite faim', '1'),
        (369, 'scones', 'Wraps Poulet', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un wraps Poulet. Utile en cas de petite faim', '1'),
        (370, 'chiacchiere', 'Chiacchiere', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Un chiacchiere, patisserie italienne. Utile en cas de petite faim', '1'),
        (371, 'croissant', 'Onions Rings', 3, 0, 1, 'eat', 1, 1, 'eat', null, null, null, null, 'Des oignons rings. Utile en cas de petite faim', '1'),

        (372, 'pates', 'Pates', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Des pates. Utile en cas de faim', '1'),
        (373, 'escalopem', 'Escalope milanaise', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une escalope milanaise. Utile en cas de faim', '1'),
        (374, 'ossobuco', 'Ossobuco', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un ossobuco. Utile en cas de faim', '1'),
        (375, 'bruscheta', 'Bruscheta', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une bruscheta. Utile en cas de faim', '1'),
        (376, 'bruschetta', 'Bruschetta a la tomate', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une bruscheta à la tomate. Utile en cas de faim', '1'),
        (377, 'tomatemoz', 'Tomate Mozzarella', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Des tomates mozzarella. Utile en cas de faim', '1'),
        (378, 'croqueparm', 'Croque Parm''accia', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un croque parm''accia. Utile en cas de faim', '1'),
        (379, 'tiramisug', 'Tiramisu', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un tiramisu. Utile en cas de faim', '1'),
        (380, 'pannacotta', 'Panna cotta', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une panna cotta. Utile en cas de faim', '1'),
        (381, 'upnatom', 'Burger Veggie', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un burger veggie. Utile en cas de faim', '1'),
        (382, 'kebab', 'Double Wooper', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un double wooper. Utile en cas de faim', '1'),
        (383, 'risotto', 'Risotto', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un risotto. Utile en cas de faim', '1'),
        (384, 'kefta', 'Cheeseburger', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un cheeseburger. Utile en cas de faim', '1'),
        (385, 'kebab2', 'Chicken Burger', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un chicken burger. Utile en cas de faim', '1'),
        (386, 'minestrone', 'Minestrone a la Milanaise', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un Minestrone. Utile en cas de faim', '1'),
        (387, 'lasagne', 'Lasagne', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Des lasagne. Utile en cas de faim', '1'),
        (388, 'bourguignon', 'Bacon Burger', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un bacon burger. Utile en cas de faim', '1'),
        (389, 'blanquette', 'Salade Beef', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une Salade Beef. Utile en cas de faim', '1'),
        (390, 'moules', 'Dorade grillée', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Une Dorade grillée. Utile en cas de faim', '1'),
        (391, 'saucisse_cuite', 'Macaroni au fromage', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Macaroni au fromage. Utile en cas de faim', '1'),
        (392, 'steak_cuit', 'Entrecote', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Entrecote. Utile en cas de faim', '1'),
        (393, 'cotelette_cuite', 'Trio de brochettes', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Trio de brochettes. Utile en cas de faim', '1'),

        (394, 'burger', 'Atom Burger', 3, 0, 1, 'eat', 2, 2, 'eat', null, null, null, null, 'Un atom burger. Utile en cas de grosse faim', '1'),

        (395, 'pizza', 'Pizza', 50, 0, 1, 'eatbox', 3, 3, 'eatbox', null, null, null, null, 'Une pizza en boite. Permet de couper 5 parts de pizza', '1'),
        (396, 'atombox', 'Box atomic frites', 10, 0, 1, 'eatbox', 3, 3, 'eatbox', null, null, null, null, 'Une box atomique. Contient un burger, des frites et une glace', '1'),
        (397, 'atombox2', 'Box atomic onions', 10, 0, 1, 'eatbox', 3, 3, 'eatbox', null, null, null, null, 'Une box atomique. Contient un burger, des oignon rings et une glace', '1'),
        (398, 'atombox3', 'Box atomic salade', 10, 0, 1, 'eatbox', 3, 3, 'eatbox', null, null, null, null, 'Une box atomique. Contient un burger, une salade et une glace', '1');


insert into items (`name`, label, `limit`, `rare`, `can_remove`, `type`, `x`, `y`, `category`, `componentTint`, `componentHash`, `backpackModel`, `backgroundTexture`, `description`, `weight`)
values
  ('clip', 'Chargeur', 10, 0, 1, 'accessoire', 1, 1, 'accessoire', null, null, null, null, 'Un chargeur de balle permettant de recharger l''arme en main', '1')
;

-- Components armes
-- A faire plus tard

-- ('silencieux', 'Silencieux', 133, 0, 133, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('flashlight', 'Lampe', 134, 0, 134, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('grip', 'Poignee', 135, 0, 135, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('yusuf', 'Skin de luxe', 136, 0, 136, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('scope', 'Scope', 141, 0, 141, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('advanced_scope', 'Advanced Scope', 142, 0, 142, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('extended_magazine', 'Extended Magazine', 144, 0, 144, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('very_extended_magazine', 'Very Extended Magazine', 145, 0, 145, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('nvg', 'Standard NVG', 146, 0, 146, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
-- ('advanced_nvg', 'Advanced NVG', 147, 0, 147, 'accessoire', 1, 1, 'misc', null, null, null, null, 'An item', '1'),
