SitOnProp = {}

SitOnProp.objects = {
	ButtonToStandUp = 23, -- // Default: F -- // https://docs.fivem.net/game-references/controls/
	SitAnimation = {anim='PROP_HUMAN_SEAT_CHAIR_MP_PLAYER'},
	-- SitAnimationCommandList = {
	-- 	'e sitchair1',
	-- 	'e sitchair2',
	-- 	'e sitchair3',
	-- 	'e sitchair4',
	-- 	'e sitchair5',
	-- 	'e sitchair6',
	-- 	'e sitchair7',
	-- },
	locations = {
		{objName='xm_prop_x17_corp_offchair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, type='chair'},
		{objName='ex_prop_offchair_exec_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.1, direction=180.0, type='chair'},
		{objName='bkr_prop_weed_chair_01a', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='ba_prop_int_edgy_stool', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=0.0, type='chair'},
		{objName='ba_prop_battle_club_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.1, direction=180.0, type='chair'},
		{objName='v_serv_ct_chair02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, type='chair3'},
		{objName='prop_off_chair_04', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, type='chair'},
		{objName='prop_off_chair_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, type='chair'},
		{objName='prop_off_chair_05', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, type='chair'},
		{objName='v_ilev_leath_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, type='chair'},
		{objName='v_corp_offchair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, type='chair'},
		{objName='Prop_Off_Chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_bench_01a', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_01b', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_01c', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=0.0, type='bench'},
		{objName='prop_bench_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_04', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_05', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=250.0, type='bench'},
		{objName='prop_bench_06', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_08', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_09', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_10', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_bench_11', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_fib_3b_bench', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_ld_bench01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='prop_wait_bench_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='hei_prop_heist_off_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='hei_prop_hei_skid_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_01a', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_01b', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_04a', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair3'},
		{objName='prop_chair_04b', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair2'},
		{objName='prop_chair_05', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_06', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_08', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_09', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chair_10', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_chateau_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_clown_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_cs_office_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_direct_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_direct_chair_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_gc_chair02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_off_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_off_chair_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_off_chair_04', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_off_chair_04b', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_off_chair_04_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_off_chair_05', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_old_deck_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_old_wood_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_rock_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_skid_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_skid_chair_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_skid_chair_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_sol_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_wheelchair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_wheelchair_01_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_armchair_01_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_clb_officechair_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_dinechair_01_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_ilev_p_easychair_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_soloffchair_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_yacht_chair_01_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_club_officechair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_corp_bk_chair3', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_corp_cd_chair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_corp_offchair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_chair02_ped', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_p_easychair', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ret_gc_chair03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_ld_farm_chair01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_04_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_05_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_06_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_leath_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_01_chr_a', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, type='chair'},
		{objName='prop_table_01_chr_b', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_02_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_03b_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_table_03_chr', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_torture_ch_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_fh_dineeamesa', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_fh_kitchenstool', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_tort_stool', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_fh_kitchenstool', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_fh_kitchenstool', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='hei_prop_yah_seat_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='hei_prop_yah_seat_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='hei_prop_yah_seat_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_waiting_seat_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_yacht_seat_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_yacht_seat_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_yacht_seat_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_hobo_seat_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_rub_couch01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='miss_rub_couch_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_ld_farm_couch01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_ld_farm_couch02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_rub_couch03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_rub_couch04', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_lev_sofa_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_res_sofa_l_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_v_med_p_sofa_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='p_yacht_sofa_01_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_m_sofa', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_res_tre_sofa_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_tre_sofa_mess_a_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_tre_sofa_mess_b_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_tre_sofa_mess_c_s', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_roller_car_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='prop_roller_car_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_ilev_ph_bench', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='bench'},
		{objName='ex_prop_offchair_exec_04', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='ex_prop_offchair_exec_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.16, direction=180.0, type='chair'},
		{objName='vw_prop_vw_offchair_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='vw_prop_casino_chair_01a', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=0.0, type='chair'},
		{objName='vw_prop_casino_track_chair_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=0.0, type='chair'},
		{objName='ba_prop_battle_club_chair_03', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.2, direction=180.0, type='chair'},
		{objName='ba_prop_battle_club_chair_02', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.2, direction=180.0, type='chair'},
		{objName='prop_bar_stool_01', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, type='chair'},
		{objName='v_res_m_l_chair1', verticalOffsetX=-0.1, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='bkr_prop_biker_boardchair01', verticalOffsetX=0.06, verticalOffsetY=0.0, verticalOffsetZ=0.1, direction=180.0, type='chair'},
		{objName=1816935351, verticalOffsetX=0.06, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName=-212710979, verticalOffsetX=0.06, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName=1889748069, verticalOffsetX=0.06, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName=1577885496, verticalOffsetX=0.06, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, type='chair'},
		{objName='v_res_fa_chair01', verticalOffsetX=0.06, verticalOffsetY=-0.0, verticalOffsetZ=-0.3, direction=180.0, type='chair'},
		{objName='gn_hh_tabouret', verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.8, direction=180.0, type='chair'},
		{objName=1840174940, verticalOffsetX=0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.8, direction=180.0, type='chair'},
		{objName=839195237, verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, type='chair'},
		{objName=-921867112, verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, type='chair'},
		{objName=-1825439518, verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, type='chair'},
		{objName=-139366965, verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=180.0, type='chair'},
		{objName=3208442854, verticalOffsetX=0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.82, direction=180.0, type='chair'}
	}
}

SitOnProp.Text = {
	RotateLeft = "~INPUT_CELLPHONE_LEFT~ Tourner à gauche ",
	RotateRight = "~INPUT_CELLPHONE_RIGHT~ Tourner à droite ",
	Standup = "~r~F~w~ Se lever",
}